#!/bin/sh 

echo "== Update opkg ==" 
opkg update 
echo "== Install Python 3 ==" 
opkg install python3 
python3 --version 

echo "== Install Python libraries (Tornado, WebSocket, OpenSSL) ==" 
opkg install python3-tornado \ 
             python3-websocket-client \ 
             python3-websockets \ 
             python3-pyopenssl 

echo "== Install pip ==" 
opkg install python3-pip 
pip3 --version 

echo "== Install UniversalGPIO using pip ==" 
pip3 install UniversalGPIO 