#!/bin/sh /etc/rc.common

START=99
STOP=10

start() {
    echo "Starting server..."
    cd /usr/server
    nohup python3 server.py 5001 192.168.144.15 >> /var/log/server.log 2>&1 &
    echo $! > /var/run/server.pid
    echo "Server started, PID=$(cat /var/run/server.pid)."
}

stop() {
    echo "Stopping server..."
    if [ -f /var/run/server.pid ]; then
        PID=$(cat /var/run/server.pid)
        kill "$PID" 2>/dev/null
        rm -f /var/run/server.pid
        echo "Server (PID=$PID) stopped."
    else
        echo "File /var/run/server.pid does not exist - the server might not have been run."
    fi
}

